/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import BUS.BAO_HANH_XE_BUS;
import BUS.KHACH_HANG_BUS;
import BUS.XE_MAY_BUS;
import DTO.BAO_HANH_XE_DTO;
import DTO.KHACH_HANG_DTO;
import DTO.XE_MAY_DTO;
import java.awt.event.ActionEvent;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.Date;
import java.util.Random;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import static javax.xml.stream.XMLStreamConstants.CHARACTERS;

/**
 *
 * @author 84865
 */
public class BAO_HANH_GUI extends javax.swing.JFrame {

    /**
     * Creates new form BaoHanhXe_GUI
     */
    private BAO_HANH_XE_BUS bao_HANH_XE_BUS = new BAO_HANH_XE_BUS();
    private KHACH_HANG_BUS khach_Hang_BUS = new KHACH_HANG_BUS();
    private XE_MAY_BUS xe_MAY_BUS = new XE_MAY_BUS();
    // public static String ma_nv_user = "MNV12345";

    public BAO_HANH_GUI() {
        initComponents();
        this.setVisible(true);
        loadAllBaoHanhXe();
        this.setLocationRelativeTo(null);
        start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblBaoHanhXe = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        txtMaBaoHanh = new javax.swing.JTextField();
        cbbMaXe = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cbbMaKhachHang = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtNgayNhanXe = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtNgayTraXe = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tareMoTa = new javax.swing.JTextArea();
        btnThem = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        cbbTimKiemTheo = new javax.swing.JComboBox<>();
        txtTimKiem = new javax.swing.JTextField();
        btnTim = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        btnExit = new javax.swing.JButton();
        txtMaNhanVien = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/Hopstarter-Soft-Scraps-Gear.72.png"))); // NOI18N
        jLabel1.setText("BẢO HÀNH XE MÁY");

        tblBaoHanhXe.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][] {

                },
                new String[] {
                        "STT", "Mã Bảo Hành", "Mã Xe", "Mã Khách Hàng", "Mã Nhân Viên", "Ngày Nhận Xe", "Ngày Trả Xe",
                        "Mô Tả"
                }));
        tblBaoHanhXe.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblBaoHanhXeMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblBaoHanhXe);

        jLabel2.setText("Mã Bảo Hành");

        txtMaBaoHanh.setBackground(new java.awt.Color(102, 102, 102));
        txtMaBaoHanh.setForeground(new java.awt.Color(255, 255, 255));

        jLabel3.setText("Mã Xe");

        jLabel4.setText("Mã Nhân Viên");

        jLabel5.setText("Mã Khách Hàng");

        jLabel6.setText("Ngày Nhận Xe");

        txtNgayNhanXe.setBackground(new java.awt.Color(102, 102, 102));
        txtNgayNhanXe.setForeground(new java.awt.Color(255, 255, 255));

        jLabel7.setText("Ngày Trả Xe");

        jLabel9.setText("Mô tả");

        tareMoTa.setColumns(20);
        tareMoTa.setRows(5);
        jScrollPane2.setViewportView(tareMoTa);

        btnThem.setIcon(new javax.swing.ImageIcon(
                getClass().getResource("/IMG/Oxygen-Icons.org-Oxygen-Actions-list-add-user.16.png"))); // NOI18N
        btnThem.setText("Thêm");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        btnSua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/Etherbrian-Webuosities-Fix-it.16.png"))); // NOI18N
        btnSua.setText("Sửa");
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });

        btnXoa.setIcon(new javax.swing.ImageIcon(
                getClass().getResource("/IMG/Oxygen-Icons.org-Oxygen-Actions-window-close.16.png"))); // NOI18N
        btnXoa.setText("Xóa");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        btnReset.setIcon(new javax.swing.ImageIcon(
                getClass().getResource("/IMG/Bootstrap-Bootstrap-Bootstrap-arrow-return-right.16.png"))); // NOI18N
        btnReset.setText("Reset");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        jLabel8.setText("Tìm Kiếm Theo");

        cbbTimKiemTheo
                .setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mã Khách Hàng", "Mã Bảo Hành", " " }));
        cbbTimKiemTheo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbbTimKiemTheoActionPerformed(evt);
            }
        });

        btnTim.setText("Tìm");
        btnTim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimActionPerformed(evt);
            }
        });

        jLabel10.setText("Tìm Kiếm :");

        btnExit.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnExit.setIcon(new javax.swing.ImageIcon(
                getClass().getResource("/IMG/Oxygen-Icons.org-Oxygen-Actions-window-close.16.png"))); // NOI18N
        btnExit.setText("EXIT");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        txtMaNhanVien.setBackground(new java.awt.Color(102, 102, 102));
        txtMaNhanVien.setForeground(new java.awt.Color(204, 204, 204));
        txtMaNhanVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMaNhanVienActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 107,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(415, 415, 415)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 440,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(layout.createSequentialGroup()
                                .addGap(34, 34, 34)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel5)
                                        .addComponent(jLabel4)
                                        .addComponent(jLabel2)
                                        .addComponent(jLabel3))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtMaBaoHanh)
                                        .addComponent(cbbMaXe, 0, 224, Short.MAX_VALUE)
                                        .addComponent(txtMaNhanVien)
                                        .addComponent(cbbMaKhachHang, 0, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                Short.MAX_VALUE))
                                .addGap(141, 141, 141)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel6)
                                        .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGap(43, 43, 43)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING,
                                                javax.swing.GroupLayout.PREFERRED_SIZE, 213,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout
                                                .createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addComponent(txtNgayTraXe, javax.swing.GroupLayout.DEFAULT_SIZE, 213,
                                                        Short.MAX_VALUE)
                                                .addComponent(txtNgayNhanXe)))
                                .addGap(32, 32, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(btnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 80,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(btnThem)
                                        .addComponent(jLabel10)
                                        .addComponent(jLabel8))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(layout.createSequentialGroup()
                                                        .addGap(38, 38, 38)
                                                        .addGroup(layout
                                                                .createParallelGroup(
                                                                        javax.swing.GroupLayout.Alignment.LEADING)
                                                                .addComponent(btnReset)
                                                                .addComponent(btnSua,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE, 78,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout
                                                        .createSequentialGroup()
                                                        .addComponent(txtTimKiem,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE, 209,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addPreferredGap(
                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(btnTim)))
                                        .addComponent(cbbTimKiemTheo, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(164, 164, 164))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jScrollPane1)
                                .addContainerGap()));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addContainerGap()
                                                .addComponent(jLabel1))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(61, 61, 61)
                                                .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 40,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(68, 68, 68)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 276,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout
                                                .createSequentialGroup()
                                                .addComponent(jLabel10)
                                                .addGap(19, 19, 19)
                                                .addGroup(layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(jLabel8)
                                                        .addComponent(cbbTimKiemTheo,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout
                                                .createSequentialGroup()
                                                .addGroup(layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addGroup(layout.createParallelGroup(
                                                                        javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addGroup(layout.createSequentialGroup()
                                                                                .addComponent(jLabel6)
                                                                                .addGap(6, 6, 6))
                                                                        .addGroup(
                                                                                javax.swing.GroupLayout.Alignment.TRAILING,
                                                                                layout.createParallelGroup(
                                                                                        javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                        .addComponent(btnTim)
                                                                                        .addComponent(txtTimKiem,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                                .addGap(25, 25, 25))
                                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout
                                                                .createSequentialGroup()
                                                                .addGroup(layout.createParallelGroup(
                                                                        javax.swing.GroupLayout.Alignment.TRAILING)
                                                                        .addComponent(txtNgayNhanXe,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                34,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addGroup(layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                .addComponent(jLabel2,
                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                        28,
                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addComponent(txtMaBaoHanh,
                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                        28,
                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                                .addGap(16, 16, 16)))
                                                .addGap(10, 10, 10)
                                                .addGroup(layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(cbbMaXe, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(txtNgayTraXe,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE, 36,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jLabel7))))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addGroup(layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(cbbMaKhachHang,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE, 32,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(34, 34, 34)
                                                .addGroup(layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(txtMaNhanVien,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE, 35,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                35, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(0, 0, Short.MAX_VALUE))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(40, 40, 40)
                                                .addGroup(layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jLabel9)
                                                        .addComponent(jScrollPane2,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE, 116,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(0, 0, Short.MAX_VALUE))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(31, 31, 31)
                                                .addGroup(layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(btnThem)
                                                        .addComponent(btnSua))
                                                .addGap(61, 61, 61)
                                                .addGroup(layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(btnXoa)
                                                        .addComponent(btnReset))
                                                .addGap(36, 42, Short.MAX_VALUE)))));

        pack();
        this.setBackground(new java.awt.Color(204, 255, 255));
    }// </editor-fold>//GEN-END:initComponents

    private void start() {
        tblBaoHanhXe.setDefaultEditor(Object.class, null); // Không cho phép chỉnh sửa giá trị của các row trực tiếp
                                                           // trong bảng
        txtMaNhanVien.setEditable(false);
        txtMaBaoHanh.setEditable(false);
        txtNgayNhanXe.setEditable(false);
        txtMaNhanVien.setText("NV tài khoản đăng nhập");
        txtMaBaoHanh.setText("Mã Bảo Hành Mới");

        ArrayList<KHACH_HANG_DTO> arrKhachHang = new ArrayList<KHACH_HANG_DTO>();
        arrKhachHang = khach_Hang_BUS.getALLKhachHang();
        for (KHACH_HANG_DTO khachHang : arrKhachHang) {
            cbbMaKhachHang.addItem(khachHang.getMA_KH());
        }

        // String [][] data= xe_MAY_BUS.getAllXeMay();
        // for(int i=0;i<data.length;i++){
        // cbbMaXe.addItem(data[i][0]);
        // }

        ArrayList<XE_MAY_DTO> arrXM = new ArrayList<XE_MAY_DTO>();
        arrXM = xe_MAY_BUS.getAllXeMay();
        for (XE_MAY_DTO xeMay : arrXM) {
            cbbMaXe.addItem((xeMay.getMA_XE()));
        }

    }

    // random mã bảo hành
    public String randomMABH() {
        String maBH = "";
        Random random = new Random();
        StringBuilder codeBuilder = new StringBuilder();
        codeBuilder.append("BH");
        for (int i = 0; i < 5; i++) {
            int randomNumber = random.nextInt(10);
            codeBuilder.append(randomNumber);
        }
        maBH = codeBuilder.toString();
        return maBH;
    }

    // lấy ngày tháng năm hiện tại
    public String ngayNhan() {
        StringBuilder day = new StringBuilder();
        LocalDate currentDate = LocalDate.now();
        int dayNow = currentDate.getDayOfMonth();
        int month = currentDate.getMonthValue();
        int year = currentDate.getYear();
        day.append(dayNow + "/" + month + "/" + year);

        return day.toString();
    }

    // Check định dạng ngày tháng năm

    public Boolean checkThoiGian(String dateString) {
        SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
        sdf.setLenient(false); // Tắt tính năng tự động điều chỉnh (lenient) của SimpleDateFormat

        try {
            Date date = sdf.parse(dateString);
            String formattedDateString = sdf.format(date);

            if (formattedDateString.equals(dateString)) {

                return true;
            } else {

                return false;
            }
        } catch (ParseException ex) {

            return false;
        }
    }

    // check ngày trả > ngày nhanak
    private boolean checkNgayTra() {
        String ngayTraXe = txtNgayTraXe.getText();
        LocalDate date1 = LocalDate.parse(ngayTraXe, DateTimeFormatter.ofPattern("dd/MM/yyyy"));
        System.out.println(ngayNhan());
        // Lấy ngày từ trường văn bản thứ hai
        String ngayNhanXe = "";
        if (txtNgayNhanXe.getText().trim().equals("")) {
            ngayNhanXe = ngayNhan();

        } else {
            ngayNhanXe = txtNgayNhanXe.getText();
        }
        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("d/M/yyyy");
        LocalDate date2 = LocalDate.parse(ngayNhanXe, formatter);

        // Chuyển đổi định dạng ngày sang "dd/MM/yyyy"
        String formattedDate = date2.format(DateTimeFormatter.ofPattern("dd/MM/yyyy"));
        date2 = LocalDate.parse(formattedDate, DateTimeFormatter.ofPattern("dd/MM/yyyy"));

        // So sánh 2 ngày với nhau
        if (date1.isBefore(date2)) {
            return false;
        } else if (date1.isAfter(date2)) {
            return true;
        } else {
            return true;
        }

    }

    // check các txt thêm
    private boolean checkThem() {
        if (!txtMaBaoHanh.getText().equals("Mã Bảo Hành Mới")) {
            JOptionPane.showMessageDialog(rootPane, "Không được Thêm Mã Bảo Hành mới :Chỉ sửa hoặc xóa");
            txtMaBaoHanh.setText("");
            txtNgayNhanXe.setText("");
            txtNgayTraXe.setText("");
            txtTimKiem.setText("");
            tareMoTa.setText("");
            cbbMaKhachHang.setSelectedIndex(0);
            cbbMaKhachHang.removeAllItems();
            cbbMaXe.setSelectedIndex(0);
            cbbMaXe.removeAllItems();
            cbbTimKiemTheo.setSelectedIndex(0);
            removeALlBaoHanhXe();
            loadAllBaoHanhXe();
            start();
            return false;
        }
        if (txtNgayTraXe.getText().equals("")) {

            JOptionPane.showMessageDialog(rootPane, "Không được để trống ngày trả xe");
            return false;
        }
        if (tareMoTa.getText().equals("")) {
            JOptionPane.showMessageDialog(rootPane, "Không được để trống mô tả");
            return false;
        }
        if (!checkThoiGian(txtNgayTraXe.getText())) {
            JOptionPane.showMessageDialog(rootPane, "Ngày trả xe có dạng dd/MM//yyyy . Vui lòng nhập đúng định dạng");
            return false;
        }
        if (!checkNgayTra()) {
            JOptionPane.showMessageDialog(rootPane, "Ngày trả xe phải sau hoặc bằng ngày nhận xe ");
            return false;
        }

        return true;
    }

    // button thêm
    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnThemActionPerformed
        // TODO add your handling code here:
        ArrayList<BAO_HANH_XE_DTO> arrBaoHanhXe = new ArrayList<BAO_HANH_XE_DTO>();
        arrBaoHanhXe = bao_HANH_XE_BUS.getAllHangXe();
        BAO_HANH_XE_DTO bao_Hanh_Xe_DTO = new BAO_HANH_XE_DTO();
        String randomMBH = randomMABH();
        // kiểm tra random mã bảo hành

        bao_Hanh_Xe_DTO.setMaBaoHanh(randomMBH);
        bao_Hanh_Xe_DTO.setMaKhachHang((String) cbbMaKhachHang.getSelectedItem());
        bao_Hanh_Xe_DTO.setMaNhanVien(Login_GUI.id_user);
        bao_Hanh_Xe_DTO.setMaXe((String) cbbMaXe.getSelectedItem());
        bao_Hanh_Xe_DTO.setMoTa(tareMoTa.getText());
        bao_Hanh_Xe_DTO.setNgayNhanXe(ngayNhan());
        bao_Hanh_Xe_DTO.setNgayTraXe(txtNgayTraXe.getText());

        System.out.println(randomMBH);
        System.out.println(ngayNhan());

        BAO_HANH_XE_BUS bao_Hanh_Xe_BUS = new BAO_HANH_XE_BUS();
        if (checkThem()) {
            bao_Hanh_Xe_BUS.addBaoHanhXe(bao_Hanh_Xe_DTO);
            removeALlBaoHanhXe();
            loadAllBaoHanhXe();
            JOptionPane.showMessageDialog(rootPane, "Thêm thành công!!(Mã bảo hành" + randomMBH + ")");
            btnResetActionPerformed(evt);
        }

    }// GEN-LAST:event_btnThemActionPerformed

    // sửa check
    private boolean checkSua() {
        if (txtMaBaoHanh.getText().equalsIgnoreCase("Mã Bảo Hành Mới")) {
            JOptionPane.showMessageDialog(rootPane, "Vui lòng chọn 1 đơn bảo hành để sửa");
            return false;
        }
        if (txtNgayTraXe.getText().equals("")) {
            JOptionPane.showMessageDialog(rootPane, "Không được để trống ngày trả xe");
            return false;

        }
        if (tareMoTa.getText().equals("")) {
            JOptionPane.showMessageDialog(rootPane, "Không được để trống mô tả");
            return false;

        }
        if (!checkThoiGian(txtNgayTraXe.getText())) {
            JOptionPane.showMessageDialog(rootPane, "Ngày trả xe có dạng dd/MM//yyyy . Vui lòng nhập đúng định dạng");
            return false;
        }
        if (!checkNgayTra()) {
            JOptionPane.showMessageDialog(rootPane, "Ngày trả xe phải sau hoặc bằng ngày nhận xe ");
            return false;
        }

        return true;

    }

    // sửa button
    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnSuaActionPerformed
        // TODO add your handling code here:
        ArrayList<BAO_HANH_XE_DTO> arrBaoHanhXe = new ArrayList<BAO_HANH_XE_DTO>();
        arrBaoHanhXe = bao_HANH_XE_BUS.getAllHangXe();
        BAO_HANH_XE_DTO bao_Hanh_Xe_DTO = new BAO_HANH_XE_DTO();
        // TẠO 1 thằng mới lấy dữ liệu cần sửa
        bao_Hanh_Xe_DTO.setMaBaoHanh(txtMaBaoHanh.getText());
        bao_Hanh_Xe_DTO.setMaKhachHang((String) cbbMaKhachHang.getSelectedItem());
        bao_Hanh_Xe_DTO.setMaNhanVien(txtMaNhanVien.getText());
        bao_Hanh_Xe_DTO.setMaXe((String) cbbMaXe.getSelectedItem());
        bao_Hanh_Xe_DTO.setMoTa(tareMoTa.getText());
        bao_Hanh_Xe_DTO.setNgayNhanXe(txtNgayNhanXe.getText());
        bao_Hanh_Xe_DTO.setNgayTraXe(txtNgayTraXe.getText());

        // truyền lại bus
        BAO_HANH_XE_BUS bao_Hanh_Xe_BUS = new BAO_HANH_XE_BUS();
        if (checkSua()) {
            bao_Hanh_Xe_BUS.editBaoHanhXe(bao_Hanh_Xe_DTO);
            removeALlBaoHanhXe();
            loadAllBaoHanhXe();
            JOptionPane.showMessageDialog(rootPane, "Sửa thành công!!");
            btnResetActionPerformed(evt);
        }

    }// GEN-LAST:event_btnSuaActionPerformed

    // check xóa
    private boolean checkXoa() {
        if (txtMaBaoHanh.getText().equalsIgnoreCase("Mã Bảo Hành Mới")) {
            JOptionPane.showMessageDialog(rootPane, "Vui lòng chọn 1 đơn bảo hành để xóa");
            return false;
        }
        if (txtNgayTraXe.getText().equals("")) {
            JOptionPane.showMessageDialog(rootPane, "Vui lòng không xóa dữ liệu của đơn muốn xóa");
            return false;

        }
        if (tareMoTa.getText().equals("")) {
            JOptionPane.showMessageDialog(rootPane, "Vui lòng không xóa dữ liệu của đơn muốn xóa ");
            return false;

        }

        return true;

    }

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnExitActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }// GEN-LAST:event_btnExitActionPerformed

    private void cbbTimKiemTheoActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_cbbTimKiemTheoActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_cbbTimKiemTheoActionPerformed

    // button tìm kiếm
    private void btnTimActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnTimActionPerformed
        // TODO add your handling code here:
        if (txtTimKiem.getText().equals("")) {
            JOptionPane.showMessageDialog(rootPane, "Không được để trống ô tìm kiếm");
        } else {
            ArrayList<BAO_HANH_XE_DTO> arrBaoHanhXe = new ArrayList<BAO_HANH_XE_DTO>();
            arrBaoHanhXe = bao_HANH_XE_BUS.getAllHangXe();
            removeALlBaoHanhXe();
            int selectedValue = cbbTimKiemTheo.getSelectedIndex();
            if (selectedValue == 0) {
                for (int i = 0; i < arrBaoHanhXe.size(); i++) {
                    BAO_HANH_XE_DTO bao_HANH_XE_DTO = arrBaoHanhXe.get(i);
                    if (bao_HANH_XE_DTO.getMaKhachHang().toLowerCase().contains(txtTimKiem.getText().toLowerCase())) {
                        Object[] newrow = { i + 1, bao_HANH_XE_DTO.getMaBaoHanh(), bao_HANH_XE_DTO.getMaXe(),
                                bao_HANH_XE_DTO.getMaKhachHang(), bao_HANH_XE_DTO.getMaNhanVien(),
                                bao_HANH_XE_DTO.getNgayNhanXe(), bao_HANH_XE_DTO.getNgayTraXe(),
                                bao_HANH_XE_DTO.getMoTa() };
                        DefaultTableModel model = (DefaultTableModel) tblBaoHanhXe.getModel();
                        model.addRow(newrow);
                    }
                }
            } else if (selectedValue == 1) {
                for (int i = 0; i < arrBaoHanhXe.size(); i++) {
                    BAO_HANH_XE_DTO bao_HANH_XE_DTO = arrBaoHanhXe.get(i);
                    if (bao_HANH_XE_DTO.getMaBaoHanh().toLowerCase().contains(txtTimKiem.getText().toLowerCase())) {
                        Object[] newrow = { i + 1, bao_HANH_XE_DTO.getMaBaoHanh(), bao_HANH_XE_DTO.getMaXe(),
                                bao_HANH_XE_DTO.getMaKhachHang(), bao_HANH_XE_DTO.getMaNhanVien(),
                                bao_HANH_XE_DTO.getNgayNhanXe(), bao_HANH_XE_DTO.getNgayTraXe(),
                                bao_HANH_XE_DTO.getMoTa() };
                        DefaultTableModel model = (DefaultTableModel) tblBaoHanhXe.getModel();
                        model.addRow(newrow);
                    }
                }
            }
        }

    }// GEN-LAST:event_btnTimActionPerformed

    // button reset
    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnResetActionPerformed
        // TODO add your handling code here:
        txtMaBaoHanh.setText("");
        txtNgayNhanXe.setText("");
        txtNgayTraXe.setText("");
        txtTimKiem.setText("");
        tareMoTa.setText("");
        cbbMaKhachHang.setSelectedIndex(0);
        cbbMaKhachHang.removeAllItems();
        cbbMaXe.setSelectedIndex(0);
        cbbMaXe.removeAllItems();
        cbbTimKiemTheo.setSelectedIndex(0);
        removeALlBaoHanhXe();
        loadAllBaoHanhXe();
        start();
    }// GEN-LAST:event_btnResetActionPerformed

    // click vào 1 dòng trong bảng
    private void tblBaoHanhXeMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_tblBaoHanhXeMouseClicked
        // TODO add your handling code here:
        if (evt.getClickCount() == 1) {
            JTable target = (JTable) evt.getSource();
            int row = target.getSelectedRow(); // lấy chỉ số dòng được chọn

            txtMaBaoHanh.setText((String) tblBaoHanhXe.getValueAt(row, 1));

            for (int i = 0; i < cbbMaXe.getItemCount(); i++) {
                if (cbbMaXe.getItemAt(i).equals(tblBaoHanhXe.getValueAt(row, 2))) {
                    cbbMaXe.setSelectedIndex(i);
                    break;
                }
            }

            for (int i = 0; i < cbbMaKhachHang.getItemCount(); i++) {
                if (cbbMaKhachHang.getItemAt(i).equals(tblBaoHanhXe.getValueAt(row, 3))) {
                    cbbMaKhachHang.setSelectedIndex(i);
                    break;
                }
            }

            txtNgayNhanXe.setText((String) tblBaoHanhXe.getValueAt(row, 5));
            txtNgayTraXe.setText((String) tblBaoHanhXe.getValueAt(row, 6));
            tareMoTa.setText((String) tblBaoHanhXe.getValueAt(row, 7));
            txtMaNhanVien.setText((String) tblBaoHanhXe.getValueAt(row, 4));

        }
    }// GEN-LAST:event_tblBaoHanhXeMouseClicked

    private void txtMaNhanVienActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_txtMaNhanVienActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_txtMaNhanVienActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnXoaActionPerformed

        String maXoa = txtMaBaoHanh.getText();

        // truyền lại bus
        BAO_HANH_XE_BUS bao_Hanh_Xe_BUS = new BAO_HANH_XE_BUS();
        if (checkXoa()) {
            bao_Hanh_Xe_BUS.deleteBaoHanhXe(maXoa);
            removeALlBaoHanhXe();
            loadAllBaoHanhXe();
            JOptionPane.showMessageDialog(rootPane, "Xóa thành công!!");
            btnResetActionPerformed(evt);
        }
    }// GEN-LAST:event_btnXoaActionPerformed

    // load xe
    public void loadAllBaoHanhXe() {
        ArrayList<BAO_HANH_XE_DTO> arrBaoHanhXe = new ArrayList<BAO_HANH_XE_DTO>();
        arrBaoHanhXe = bao_HANH_XE_BUS.getAllHangXe();

        System.out.println(arrBaoHanhXe.size());
        for (int i = 0; i < arrBaoHanhXe.size(); i++) {
            BAO_HANH_XE_DTO bao_HANH_XE_DTO = arrBaoHanhXe.get(i);
            Object[] newrow = { i + 1, bao_HANH_XE_DTO.getMaBaoHanh(), bao_HANH_XE_DTO.getMaXe(),
                    bao_HANH_XE_DTO.getMaKhachHang(), bao_HANH_XE_DTO.getMaNhanVien(), bao_HANH_XE_DTO.getNgayNhanXe(),
                    bao_HANH_XE_DTO.getNgayTraXe(), bao_HANH_XE_DTO.getMoTa() };
            DefaultTableModel model = (DefaultTableModel) tblBaoHanhXe.getModel();
            model.addRow(newrow);
        }

    }

    // xóa thông tin bảng
    public void removeALlBaoHanhXe() {
        DefaultTableModel model = (DefaultTableModel) tblBaoHanhXe.getModel();
        model.setRowCount(0);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel.
         * For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BAO_HANH_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BAO_HANH_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BAO_HANH_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BAO_HANH_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        }
        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BAO_HANH_GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnTim;
    private javax.swing.JButton btnXoa;
    private javax.swing.JComboBox<String> cbbMaKhachHang;
    private javax.swing.JComboBox<String> cbbMaXe;
    private javax.swing.JComboBox<String> cbbTimKiemTheo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea tareMoTa;
    private javax.swing.JTable tblBaoHanhXe;
    private javax.swing.JTextField txtMaBaoHanh;
    private javax.swing.JTextField txtMaNhanVien;
    private javax.swing.JTextField txtNgayNhanXe;
    private javax.swing.JTextField txtNgayTraXe;
    private javax.swing.JTextField txtTimKiem;
    // End of variables declaration//GEN-END:variables
}
