 // Failed to get sources. Instead, stub sources have been generated by the disassembler.
 // Implementation of methods is unavailable.
 package BUS;
 import java.util.ArrayList;
import DAO.*;
import DTO.*;

 public class KHACH_HANG_BUS {
   
   KHACH_HANG_DAO khach_hang_DAO = new KHACH_HANG_DAO();

   
   public ArrayList<KHACH_HANG_DTO> getALLKhachHang ()
    {
        return khach_hang_DAO.getAllKhachHang();
    }
    
    public boolean check_MAKH (String maKH)
    {
        if (khach_hang_DAO.check_MAKH(maKH))
        {
            return true;
        }
        return false;
    }
    public boolean checkTenKH (String tenKH)
    {
        if (khach_hang_DAO.checkTenKH(tenKH))
        {
            return true;
        }
        return false;
    }

    public boolean addKhachHang(KHACH_HANG_DTO khach_hang_DTO){
        return khach_hang_DAO.addKhachHang(khach_hang_DTO);
   }

   public boolean editKhachHang (KHACH_HANG_DTO khach_hang_DTO)
    {
        return khach_hang_DAO.editKhachHang(khach_hang_DTO);
    }
    
    public boolean checkMAKhachHang (String maKH)
    {
        if (khach_hang_DAO.checkMAKhachHang(maKH))
        {
            return true;
        }
        return false;
    }


    public boolean updateKhachHang (String maKH)
    {
        return khach_hang_DAO.updateKhachHang(maKH);
    }

    public boolean deleteKhachHang (String maKH)
    {
        
        return khach_hang_DAO.deleteKhachHang(maKH);
    }

    public static ArrayList<KHACH_HANG_DTO> getAllHangXe() {
        return null;
    }
 }